const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
const AGENT_ENDPOINT = process.env.REACT_APP_AGENT_ENDPOINT;
const AGENT_TEST_ENDPOINT = process.env.REACT_APP_AGENT_TEST_ENDPOINT;

export const API_ENDPOINTS = {
  PUT_FILE: `${API_BASE_URL}/file`,
  AGENT: `${AGENT_ENDPOINT}`,
  AGENT_TEST: `${AGENT_TEST_ENDPOINT}`,
};